file:
    upload-dir: uploads

logging:
    file:
        name: /logs/spring-board-app.log
    level:
        root: info

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mappers/**/*.xml

server:
    servlet:
        context-path: /
    port: 8080

spring:
    application:
        name: spring-board-app
        version: ${version:0.1.0}

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:3.35.24.141}:3306/kmarket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME:kmarket_user}
        password: ${DB_PASSWORD}

    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    # 메일 설정도 독립시켜 spring 하위로 정렬했습니다.
    mail:
        host: smtp.gmail.com
        username: ${MAIL_USERNAME:heocoding@gmail.com}
        password: ${MAIL_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
                        required: true
                    timeout: 3000

    servlet:
        multipart:
            enabled: true
            location: src/main/resources/static/uploads
            max-file-size: 10MB
            max-request-size: 50MB

    thymeleaf:
        cache: false
        prefix: classpath:/templates/

    # 구글 소셜로그인
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope: profile, email
                        redirect-uri: "{baseUrl}/login/oauth2/code/google"